/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ma.ac.uir.tp7prof;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Najib
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCivilite = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtNom = new javax.swing.JTextField();
        jtprenom = new javax.swing.JTextField();
        jtmel = new javax.swing.JTextField();
        jcbprofession = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jsp1 = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jtCNE = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jtfid = new javax.swing.JTextField();
        Id = new javax.swing.JLabel();
        jtfSupprimer = new javax.swing.JButton();
        jtfModif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("Ajouter un participant");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 29, -1, -1));

        jLabel1.setText("Nom");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 107, -1, -1));

        jLabel2.setText("Prénom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 135, -1, -1));

        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 171, -1, -1));

        jLabel5.setText("E-mail");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 215, -1, -1));

        jLabel6.setText("Profession");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 244, -1, -1));
        getContentPane().add(jtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 104, 144, -1));
        getContentPane().add(jtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 132, 144, -1));
        getContentPane().add(jtmel, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 212, 144, -1));

        jcbprofession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professeur", "Etudiant", "Administrateur" }));
        getContentPane().add(jcbprofession, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 241, 144, -1));

        bgCivilite.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Monsieur");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 105, -1, -1));

        bgCivilite.add(jRadioButton3);
        jRadioButton3.setText("Madame");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 133, -1, -1));

        bgCivilite.add(jRadioButton4);
        jRadioButton4.setText("Mlle");
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 173, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 0));
        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 240, -1, -1));

        jsp1.setValue(20);
        getContentPane().add(jsp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 168, 144, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("CNE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 215, -1, -1));
        getContentPane().add(jtCNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 212, 79, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Lister");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "CNE", "prenom", "nom", "Profession", "Civilite", "email", "age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 76, 470, 205));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Effacer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 270, -1, -1));

        jtfid.setToolTipText("");
        jtfid.setEnabled(false);
        getContentPane().add(jtfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 76, 144, -1));

        Id.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Id.setForeground(new java.awt.Color(255, 0, 0));
        Id.setText("ID");
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 76, -1, -1));

        jtfSupprimer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtfSupprimer.setForeground(new java.awt.Color(204, 0, 0));
        jtfSupprimer.setText("Supprimer");
        jtfSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(jtfSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 271, 100, -1));

        jtfModif.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jtfModif.setForeground(new java.awt.Color(0, 102, 51));
        jtfModif.setText("Modifier");
        jtfModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfModifActionPerformed(evt);
            }
        });
        getContentPane().add(jtfModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 241, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Nom ; 
        String prenom; 
        String email; 
        String profession; 
        String civilite;
        String cne;
        
        int age;
        
        Nom = jtNom.getText();
        prenom = jtprenom.getText();
        email = jtmel.getText();
        profession = jcbprofession.getSelectedItem().toString();
        age = Integer.parseInt(jsp1.getValue().toString());
        cne = jtCNE.getText();
        
        if(jRadioButton1.isSelected())
            civilite = "Homme";
        else if(jRadioButton3.isSelected())
            civilite = "Madame";
        else 
            civilite = "Mlle";
        
        Participant p = new Participant(cne, Nom, prenom, profession, civilite, email, age);
       
        System.out.println(p.toString());
        boolean res = p.addParticipant();
        JFrame frame = null;
        if(res){
            System.out.println("ajout réussit");
            JOptionPane.showMessageDialog(frame,  "le nouveau utilisateur a été ajouté avec succes");
            this.jButton2ActionPerformed(evt);
        }else{
            JOptionPane.showMessageDialog(frame,  " Problème d'ajout du nouveau utilisateur ", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        LinkedList<Participant> l = new LinkedList<>();
        l= Participant.getAllParticipants();
        System.out.println("================================================");
        System.out.println("=========La liste des participants      ========");
        System.out.println("================================================");
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Vider le tableau avant ajout (facultatif)
        model.setRowCount(0);

        for (Participant p : l) {

            System.out.println(p.toString());

            model.addRow(new Object[] {
                p.getId(),
                p.getCne(),
                p.getPrenom(),
                p.getNom(),
                p.getProfession(),
                p.getCivilite(),
                p.getEmail(),
                p.getAge(),
            });
        }
        // solution avec build table
        /*String req = "SELECT * FROM participant ";
        Participant p = null;
	try{
            java.sql.Connection conn = Connection.connect();
            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,   ResultSet.CONCUR_UPDATABLE);
            stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(req);
            jTable1.setModel(Participant.buildTableModel(rs));
            conn.close();
            rs.close();
            stmt.close();
                       
	}catch(SQLException e){
            System.out.println("Problème durant la récupération de la liste des règles d'association");
            System.out.println("SQLException: " + e.getMessage());
            System.out.println("SQLState: "     + e.getSQLState());
	    System.out.println("VendorError: "  + e.getErrorCode());
	}
        
        */
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jtNom.setText("");
        jtCNE.setText("");
        jtmel.setText("");
        jtprenom.setText("");
        jsp1.setValue(0);
        jtfid.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int ligne = jTable1.getSelectedRow();
        jtfid.setText(""+ jTable1.getValueAt(ligne, 0));
        jtNom.setText(""+ jTable1.getValueAt(ligne, 2));
        jtCNE.setText(""+ jTable1.getValueAt(ligne, 1));
        jtmel.setText(""+  jTable1.getValueAt(ligne, 6));
        jtprenom.setText(""+ jTable1.getValueAt(ligne, 3));
        
        jsp1.setValue(Integer.parseInt( jTable1.getValueAt(ligne, 7).toString() ));
        
        
        String etat = jTable1.getValueAt(ligne, 4).toString();
        String civilite = jTable1.getValueAt(ligne, 5).toString();
           System.out.println("la civilité ||" + civilite + "||" );
        if(etat.equalsIgnoreCase("Professeur") )
            jcbprofession.setSelectedIndex(0);
        if(etat.equalsIgnoreCase("Etudiant") )
            jcbprofession.setSelectedIndex(1);
        if(etat.equalsIgnoreCase("Administrateur") )
            jcbprofession.setSelectedIndex(2);
        
        if(civilite.equalsIgnoreCase("Homme"))
            jRadioButton1.setSelected(true);
        else if(civilite.equalsIgnoreCase("Madame"))
            jRadioButton3.setSelected(true);
        else 
            jRadioButton4.setSelected(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jtfSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSupprimerActionPerformed
        int id = Integer.parseInt(jtfid.getText().toString());
        Boolean res = false;
        res = Participant.supprimerParticipant(id);
        this.jButton2ActionPerformed(evt);
        JFrame frame = null;
        if (res)
            JOptionPane.showMessageDialog(frame,  "Le participant a été supprimé avec succes ");
        
        else 
           JOptionPane.showMessageDialog(frame,  "probleme de suppression"); 
        
    }//GEN-LAST:event_jtfSupprimerActionPerformed

    private void jtfModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfModifActionPerformed
        String Nom ; 
        String prenom; 
        String email; 
        String profession; 
        String civilite;
        String cne;
        
        int age;
        int id ;
        
        Nom = jtNom.getText();
        prenom = jtprenom.getText();
        email = jtmel.getText();
        profession = jcbprofession.getSelectedItem().toString();
        age = Integer.parseInt(jsp1.getValue().toString());
        cne = jtCNE.getText();
        
        if(jRadioButton1.isSelected())
            civilite = "Homme";
        else if(jRadioButton3.isSelected())
            civilite = "Madame";
        else 
            civilite = "Mlle";
        
        id = Integer.parseInt(jtfid.getText());
        Participant p = new Participant(id, cne, Nom, prenom, profession, civilite, email, age);
        boolean res =  p.updateParticpant();
        
        this.jButton2ActionPerformed(evt);
        JFrame frame = null;
        if (res)
            JOptionPane.showMessageDialog(frame,  "Le participant a été modifié avec succes ");
        
        else 
           JOptionPane.showMessageDialog(frame,  "probleme de modification"); 
    }//GEN-LAST:event_jtfModifActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.ButtonGroup bgCivilite;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbprofession;
    private javax.swing.JSpinner jsp1;
    private javax.swing.JTextField jtCNE;
    private javax.swing.JTextField jtNom;
    private javax.swing.JButton jtfModif;
    private javax.swing.JButton jtfSupprimer;
    private javax.swing.JTextField jtfid;
    private javax.swing.JTextField jtmel;
    private javax.swing.JTextField jtprenom;
    // End of variables declaration//GEN-END:variables
}
