/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Utilisateur;

/**
 *
 * @author idber
 */
public class AdminDashboard extends javax.swing.JFrame {
    
     private static final java.util.logging.Logger logger =java.util.logging.Logger.getLogger(AdminDashboard.class.getName());
     private final Utilisateur utilisateur; // Admin connecté
     private javax.swing.JButton btnProfile;

    public AdminDashboard(Utilisateur u) {
        this.utilisateur = u;
        initComponents();
        // Affichage du nom de l’admin
        lblAdminName.setText(u.getNom() + " " + u.getPrenom());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        btnMedecins = new javax.swing.JButton();
        btnAssistants = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnPatients = new javax.swing.JButton();
        btnConsultations = new javax.swing.JButton();
        btnCategories = new javax.swing.JButton();
        btnMonthlyReport = new javax.swing.JButton();
        btnPaymentReport = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Espace Administrateur");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 0, -1, -1));

        lblAdminName.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        getContentPane().add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 54, 170, 18));

        btnMedecins.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMedecins.setText("Gérer les médecins");
        btnMedecins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedecinsActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedecins, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 103, -1, -1));

        btnAssistants.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAssistants.setText("Gérer les assistant");
        btnAssistants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssistantsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAssistants, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 103, -1, -1));

        jLabel7.setText("──────────────────────────────── Gestion Médicale ─────────────────────────");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 148, 606, -1));

        jLabel8.setText("─────────────────────────────── Gestion du Personnel ──────────────────────────");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, -1, -1));

        jLabel10.setText("────────────────────────  Rapports & Statistiques ────────────────────────────");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 235, 606, -1));

        btnPatients.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPatients.setText("Gérer les patients");
        btnPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientsActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 182, -1, -1));

        btnConsultations.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultations.setText("Gérer les consultations ");
        btnConsultations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultationsActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultations, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 182, -1, -1));

        btnCategories.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCategories.setText("Gérer les catégories ");
        btnCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriesActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 182, -1, -1));

        btnMonthlyReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMonthlyReport.setText(" Voir rapport mensuel");
        btnMonthlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlyReportActionPerformed(evt);
            }
        });
        getContentPane().add(btnMonthlyReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 269, -1, -1));

        btnPaymentReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPaymentReport.setText("Rapport des paiements");
        btnPaymentReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentReportActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaymentReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 269, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setText("Déconnexion ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 327, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Gérer Mon Profile");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText(" Connecté en tant que : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 52, -1, -1));

        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdmin.setText("Gérer les admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 103, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssistantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssistantsActionPerformed
        // TODO add your handling code here:
         new ManageAssistantsPanel(utilisateur).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAssistantsActionPerformed

    private void btnConsultationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultationsActionPerformed
        // TODO add your handling code here:
         new AppointmentPanel(utilisateur).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultationsActionPerformed

    private void btnCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriesActionPerformed
        // TODO add your handling code here:
        new CategoryPanel(utilisateur).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCategoriesActionPerformed

    private void btnMedecinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedecinsActionPerformed
        // TODO add your handling code here:
        new ManageDoctorsPanel(utilisateur).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMedecinsActionPerformed

    private void btnPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientsActionPerformed
        // TODO add your handling code here:
        new PatientPanel(utilisateur).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnPatientsActionPerformed

    private void btnMonthlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlyReportActionPerformed
        // TODO add your handling code here:
         new MonthlyReportPanel(utilisateur).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMonthlyReportActionPerformed

    private void btnPaymentReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentReportActionPerformed
        // TODO add your handling code here:
         new PaymentReportPanel(utilisateur).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPaymentReportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new LoginPanel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new UserProfilePanel(utilisateur).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        new ManageAdminsPanel(utilisateur).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
java.awt.EventQueue.invokeLater(() -> {
        JOptionPane.showMessageDialog(null,"Veuillez lancer l'application depuis LoginPanel.","Erreur", JOptionPane.ERROR_MESSAGE);});
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAssistants;
    private javax.swing.JButton btnCategories;
    private javax.swing.JButton btnConsultations;
    private javax.swing.JButton btnMedecins;
    private javax.swing.JButton btnMonthlyReport;
    private javax.swing.JButton btnPatients;
    private javax.swing.JButton btnPaymentReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAdminName;
    // End of variables declaration//GEN-END:variables
}
