/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.interfaces.UtilisateurDAO;
import dao.impl.UtilisateurDAOImpl;
import model.Utilisateur;
import model.Role;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Logger;
/**
 *
 * @author idber
 */
public class ManageDoctorsPanel extends javax.swing.JFrame {
    
        private static final Logger logger = Logger.getLogger(ManageDoctorsPanel.class.getName());

    
   private final Utilisateur utilisateur; // Admin connecté
    private final UtilisateurDAO utilisateurDAO = new UtilisateurDAOImpl();

    public ManageDoctorsPanel(Utilisateur u) {
        this.utilisateur = u;
        initComponents();
        lblAdminName.setText("Connecté : " + u.getNom() + " " + u.getPrenom());
        loadDoctors(); // Charger les médecins dès l’ouverture
    }

   private void loadDoctors() {
        try {
            LinkedList<Utilisateur> list = utilisateurDAO.getAllMedecins();

            DefaultTableModel model = (DefaultTableModel) tableDoctors.getModel();
            model.setRowCount(0);

            for (Utilisateur u : list) {
                model.addRow(new Object[]{
                        u.getId(),
                        u.getNom(),
                        u.getPrenom(),
                        u.getSpecialite(),
                        u.isDisponible() ? "Oui" : "Non"
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erreur chargement médecins");
            e.printStackTrace();
        }
    }
 private void searchDoctors() {
        String keyword = txtSearch.getText().trim().toLowerCase();

        try {
            LinkedList<Utilisateur> list = utilisateurDAO.getAllMedecins();

            DefaultTableModel model = (DefaultTableModel) tableDoctors.getModel();
            model.setRowCount(0);

            for (Utilisateur u : list) {
                String fullName = (u.getNom() + " " + u.getPrenom()).toLowerCase();

                if (fullName.contains(keyword) ||
                        u.getNom().toLowerCase().contains(keyword) ||
                        u.getPrenom().toLowerCase().contains(keyword)) {

                    model.addRow(new Object[]{
                            u.getId(),
                            u.getNom(),
                            u.getPrenom(),
                            u.getSpecialite(),
                            u.isDisponible() ? "Oui" : "Non"
                    });

                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erreur recherche !");
        } }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDoctors = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 0, 255));
        lblTitle.setText("Gestion des Médecins");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 26));

        lblAdminName.setText("Admin Connecté : ");
        getContentPane().add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 240, -1));

        jLabel1.setText("Recherche médecin :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 100, 20));

        btnSearch.setBackground(new java.awt.Color(0, 51, 204));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Rechercher");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        btnRefresh.setBackground(new java.awt.Color(51, 153, 0));
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Rafraichir");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 126, -1));

        jLabel2.setText("──────────────────TABLEAU DES MÉDECINS───────────────────");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 1005, -1));

        tableDoctors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOM", "Prénom", "Spécialité", "Disponibilité"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDoctors);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 449, 275));

        btnBack.setText("Retour");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 130, -1));

        jLabel3.setText("─────────────────────────────────────────────────────");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        btnAdd.setForeground(new java.awt.Color(0, 102, 51));
        btnAdd.setText("Ajouter");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 100, -1));

        btnEdit.setForeground(new java.awt.Color(102, 102, 0));
        btnEdit.setText("Modifier");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 130, -1));

        btnDelete.setForeground(new java.awt.Color(204, 0, 0));
        btnDelete.setText("Supprimer");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminDashboard(utilisateur).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        searchDoctors();

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadDoctors();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String nom = JOptionPane.showInputDialog(this, "Nom :");
    if (nom == null) return;

    String prenom = JOptionPane.showInputDialog(this, "Prénom :");
    if (prenom == null) return;

    String login = JOptionPane.showInputDialog(this, "Login :");
    if (login == null) return;

    String password = JOptionPane.showInputDialog(this, "Mot de passe :");
    if (password == null) return;

    String specialite = JOptionPane.showInputDialog(this, "Spécialité :");
    if (specialite == null) return;

    try {
        Utilisateur med = new Utilisateur();
        med.setNom(nom);
        med.setPrenom(prenom);
        med.setLogin(login);
        med.setPassword(password);
        med.setRole(Role.MEDECIN);
        med.setSpecialite(specialite);
        med.setDisponible(true);

        if (utilisateurDAO.createUtilisateur(med)) {
            JOptionPane.showMessageDialog(this, "Médecin ajouté !");
            loadDoctors();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur ajout médecin !");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = tableDoctors.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un médecin.");
        return;
    }

    int id = (int) tableDoctors.getValueAt(row, 0);

    try {
        Utilisateur med = utilisateurDAO.findMedecinById(id);

        String nom = JOptionPane.showInputDialog(this, "Nom :", med.getNom());
        if (nom == null) return;

        String prenom = JOptionPane.showInputDialog(this, "Prénom :", med.getPrenom());
        if (prenom == null) return;

        String login = JOptionPane.showInputDialog(this, "Login :", med.getLogin());
        if (login == null) return;

        String pass = JOptionPane.showInputDialog(this, "Mot de passe :", med.getPassword());
        if (pass == null) return;

        String specialite = JOptionPane.showInputDialog(this, "Spécialité :", med.getSpecialite());
        if (specialite == null) return;

        String dispoStr = JOptionPane.showInputDialog(this, "Disponible (oui/non) :", med.isDisponible() ? "oui" : "non");
        if (dispoStr == null) return;

        med.setNom(nom);
        med.setPrenom(prenom);
        med.setLogin(login);
        med.setPassword(pass);
        med.setSpecialite(specialite);
        med.setDisponible(dispoStr.equalsIgnoreCase("oui"));

        if (utilisateurDAO.updateUtilisateur(med)) {
            JOptionPane.showMessageDialog(this, "Médecin modifié !");
            loadDoctors();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur modification médecin !");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tableDoctors.getSelectedRow();
        if (row == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un médecin.");
        return;
    }

    int id = (int) tableDoctors.getValueAt(row, 0);

    int confirm = JOptionPane.showConfirmDialog(this,
            "Supprimer ce médecin ?", "Confirmation",
            JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            if (utilisateurDAO.deleteUtilisateur(id)) {
                JOptionPane.showMessageDialog(this, "Médecin supprimé !");
                loadDoctors();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur suppression médecin !");
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
java.awt.EventQueue.invokeLater(() -> {
        JOptionPane.showMessageDialog(null,"Veuillez lancer l'application depuis LoginPanel.","Erreur", JOptionPane.ERROR_MESSAGE);});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tableDoctors;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
