/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.interfaces.UtilisateurDAO;
import dao.impl.UtilisateurDAOImpl;
import model.Utilisateur;
import model.Role;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.LinkedList;
/**
 *
 * @author idber
 */
public class ManageAdminsPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageAdminsPanel.class.getName());
    private final Utilisateur utilisateur;
    private final UtilisateurDAO utilisateurDAO = new UtilisateurDAOImpl();

    public ManageAdminsPanel(Utilisateur u) {
        this.utilisateur = u;
        initComponents();
        lblAdminName.setText("Admin Connecté : " + u.getNom() + " " + u.getPrenom());
        loadAdmins();
    }

    //      LOAD ADMINS
    private void loadAdmins() {
        try {
            LinkedList<Utilisateur> list = utilisateurDAO.getAllAssistants(); 
            // ❗ Ton DAO n’a pas getAllAdmins → on va filtrer MANUELLEMENT

            DefaultTableModel model = (DefaultTableModel) tableAdmins.getModel();
            model.setRowCount(0);

            // ⚠️ Récupère TOUS les utilisateurs ROLE = ADMIN
            java.sql.Connection conn = db.Connection.connect();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery("SELECT * FROM Utilisateur WHERE role = 'ADMIN'");

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("nom"),
                        rs.getString("prenom"),
                        rs.getString("login")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur chargement admins");
            e.printStackTrace();
        }
    }

    //      SEARCH ADMINS
    private void searchAdmins() {
        String keyword = txtSearch.getText().trim().toLowerCase();

        try {
            DefaultTableModel model = (DefaultTableModel) tableAdmins.getModel();
            model.setRowCount(0);

            java.sql.Connection conn = db.Connection.connect();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery("SELECT * FROM Utilisateur WHERE role = 'ADMIN'");

            while (rs.next()) {
                String fullName = (rs.getString("nom") + " " + rs.getString("prenom")).toLowerCase();

                if (fullName.contains(keyword)) {
                    model.addRow(new Object[]{
                            rs.getInt("id"),
                            rs.getString("nom"),
                            rs.getString("prenom"),
                            rs.getString("login")
                    });
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur recherche !");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAdmins = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("────────────────────────────────────────────────────────");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jLabel5.setText("──────────────────────TABLEAU DES Admin──────────────────");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 480, -1));

        btnBack.setText("Retour");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 630, 100, -1));

        jLabel1.setText("Recherche admin :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        btnAdd.setForeground(new java.awt.Color(0, 102, 51));
        btnAdd.setText("Ajouter");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 100, -1));
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 92, -1));

        btnEdit.setForeground(new java.awt.Color(102, 102, 0));
        btnEdit.setText("Modifier");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, 100, -1));

        btnSearch.setText("Rechercher");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 93, -1));

        btnDelete.setForeground(new java.awt.Color(204, 0, 0));
        btnDelete.setText("Supprimer");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 110, -1));

        btnRefresh.setText("Raffraichir");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, -1, -1));

        tableAdmins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prenom", "Login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAdmins);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, 275));

        jLabel6.setText("───────────────────────────────────────────────────────");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 478, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 0, 255));
        lblTitle.setText("Gestion des Admin");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 33, -1, 26));

        lblAdminName.setText("Admin Connecté : ");
        getContentPane().add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminDashboard(utilisateur).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String nom = JOptionPane.showInputDialog(this, "Nom :");
        if (nom == null) return;

        String prenom = JOptionPane.showInputDialog(this, "Prénom :");
        if (prenom == null) return;

        String login = JOptionPane.showInputDialog(this, "Login :");
        String pass = JOptionPane.showInputDialog(this, "Mot de passe :");

        try {
            Utilisateur admin = new Utilisateur();
            admin.setNom(nom);
            admin.setPrenom(prenom);
            admin.setLogin(login);
            admin.setPassword(pass);
            admin.setRole(Role.ADMIN);
            admin.setSpecialite(null);
            admin.setDisponible(true);

            if (utilisateurDAO.createUtilisateur(admin)) {
                JOptionPane.showMessageDialog(this, "Admin ajouté !");
                loadAdmins();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur ajout !");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int row = tableAdmins.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Sélectionnez un admin.");
            return;
        }

        int id = (int) tableAdmins.getValueAt(row, 0);

        try {
            Utilisateur admin = utilisateurDAO.findAssistantById(id); 
            // findAssistantById() retourne nom/prenom/login même si ROLE=ADMIN

            String nom = JOptionPane.showInputDialog(this, "Nom :", admin.getNom());
            if (nom == null) return;

            String prenom = JOptionPane.showInputDialog(this, "Prénom :", admin.getPrenom());
            String login = JOptionPane.showInputDialog(this, "Login :", admin.getLogin());
            String pass = JOptionPane.showInputDialog(this, "Mot de passe :", admin.getPassword());

            admin.setNom(nom);
            admin.setPrenom(prenom);
            admin.setLogin(login);
            admin.setPassword(pass);
            admin.setRole(Role.ADMIN);

            if (utilisateurDAO.updateUtilisateur(admin)) {
                JOptionPane.showMessageDialog(this, "Admin modifié !");
                loadAdmins();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur modification !");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        searchAdmins();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int row = tableAdmins.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Sélectionnez un admin.");
            return;
        }

        int id = (int) tableAdmins.getValueAt(row, 0);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Supprimer cet admin ?", "Confirmation",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (utilisateurDAO.deleteUtilisateur(id)) {
                    JOptionPane.showMessageDialog(this, "Admin supprimé !");
                    loadAdmins();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur suppression !");
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadAdmins();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {JOptionPane.showMessageDialog(null,"Veuillez lancer l'application depuis LoginPanel.","Erreur", JOptionPane.ERROR_MESSAGE);});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tableAdmins;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
