/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.interfaces.UtilisateurDAO;
import dao.impl.UtilisateurDAOImpl;
import model.Utilisateur;
import model.Role;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.LinkedList;
/**
 *
 * @author idber
 */
public class ManageAssistantsPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageAssistantsPanel.class.getName());
    private final Utilisateur utilisateur; // Admin connecté
    private final UtilisateurDAO utilisateurDAO = new UtilisateurDAOImpl();

    public ManageAssistantsPanel(Utilisateur u) {
         this.utilisateur = u;
        initComponents();
        lblAdminName.setText("Admin Connecté : " + u.getNom() + " " + u.getPrenom());
        loadAssistants();
    }

    

    /** Chargement des assistants **/
private void loadAssistants() {
        try {
            LinkedList<Utilisateur> list = utilisateurDAO.getAllAssistants();

            DefaultTableModel model = (DefaultTableModel) tableAssistants.getModel();
            model.setRowCount(0);

            for (Utilisateur u : list) {
                model.addRow(new Object[]{
                        u.getId(),
                        u.getNom(),
                        u.getPrenom(),
                        u.getLogin()
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erreur chargement assistants");
            e.printStackTrace();
        }
    }
    /** Recherche **/
private void searchAssistants() {
        String keyword = txtSearch.getText().trim().toLowerCase();

        try {
            LinkedList<Utilisateur> list = utilisateurDAO.getAllAssistants();
            DefaultTableModel model = (DefaultTableModel) tableAssistants.getModel();
            model.setRowCount(0);

            for (Utilisateur u : list) {
                String fullName = (u.getNom() + " " + u.getPrenom()).toLowerCase();

                if (fullName.contains(keyword)) {
                    model.addRow(new Object[]{
                            u.getId(),
                            u.getNom(),
                            u.getPrenom(),
                            u.getLogin()
                    });
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erreur recherche !");
        }
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAssistants = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 0, 255));
        lblTitle.setText("Gestion des Assistants");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, 26));

        lblAdminName.setText("Admin Connecté : ");
        getContentPane().add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 240, -1));

        jLabel4.setText("────────────────────────────────────────────────────────");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel5.setText("──────────────────────TABLEAU DES ASSISTANTS──────────────────");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel1.setText("Recherche assistant :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 92, -1));

        btnSearch.setText("Rechercher");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 93, -1));

        btnRefresh.setText("Raffraichir");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        tableAssistants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prenom", "Login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAssistants);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, 275));

        jLabel6.setText("───────────────────────────────────────────────────────");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 478, -1));

        btnBack.setText("Retour");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 100, -1));

        btnAdd.setForeground(new java.awt.Color(0, 102, 51));
        btnAdd.setText("Ajouter");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 90, -1));

        btnEdit.setForeground(new java.awt.Color(102, 102, 0));
        btnEdit.setText("Modifier");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 100, -1));

        btnDelete.setForeground(new java.awt.Color(204, 0, 0));
        btnDelete.setText("Supprimer");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:      
        searchAssistants();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadAssistants();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminDashboard(utilisateur).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String nom = JOptionPane.showInputDialog(this, "Nom :");
    if (nom == null) return;

    String prenom = JOptionPane.showInputDialog(this, "Prénom :");
    String login = JOptionPane.showInputDialog(this, "Login :");
    String password = JOptionPane.showInputDialog(this, "Mot de passe :");

    try {
        Utilisateur a = new Utilisateur();
        a.setNom(nom);
        a.setPrenom(prenom);
        a.setLogin(login);
        a.setPassword(password);
        a.setRole(Role.ASSISTANT);
        a.setSpecialite(null);
        a.setDisponible(true); // ✔ obligatoire

        if (utilisateurDAO.createUtilisateur(a)) {
            JOptionPane.showMessageDialog(this, "Assistant ajouté !");
            loadAssistants();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur ajout !");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
         int row = tableAssistants.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un assistant.");
        return;
    }

    int id = (int) tableAssistants.getValueAt(row, 0);

    try {
        Utilisateur u = utilisateurDAO.findAssistantById(id);

        String nom = JOptionPane.showInputDialog(this, "Nom :", u.getNom());
        if (nom == null) return;

        String prenom = JOptionPane.showInputDialog(this, "Prénom :", u.getPrenom());
        String login = JOptionPane.showInputDialog(this, "Login :", u.getLogin());
        String pass = JOptionPane.showInputDialog(this, "Mot de passe :", u.getPassword());

        u.setNom(nom);
        u.setPrenom(prenom);
        u.setLogin(login);
        u.setPassword(pass);
        u.setRole(Role.ASSISTANT);
        u.setSpecialite(null);
        u.setDisponible(true);

        if (utilisateurDAO.updateUtilisateur(u)) {
            JOptionPane.showMessageDialog(this, "Assistant modifié !");
            loadAssistants();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur modification !");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tableAssistants.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Sélectionnez un assistant.");
            return;
        }

        int id = (int) tableAssistants.getValueAt(row, 0);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Supprimer cet assistant ?", "Confirmation",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                if (utilisateurDAO.deleteUtilisateur(id)) {
                    JOptionPane.showMessageDialog(this, "Assistant supprimé !");
                    loadAssistants();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur suppression !");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {JOptionPane.showMessageDialog(null,"Veuillez lancer l'application depuis LoginPanel.","Erreur", JOptionPane.ERROR_MESSAGE);});
    }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tableAssistants;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
