/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Service.ReportService;
import dao.impl.ConsultationDAOImpl;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Utilisateur;
import report.dto.DailyRevenueDTO;
import report.dto.MonthlyReportDTO;

/**
 *
 * @author idber
 */
public class MonthlyReportPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MonthlyReportPanel.class.getName());
    private final Utilisateur utilisateur;
    private final ReportService reportService = new ReportService(new ConsultationDAOImpl());

    /**
     * Creates new form MonthlyReportPanel
     */
    public MonthlyReportPanel(Utilisateur u) {
    this.utilisateur = u;
    initComponents();

    lblAdminName.setText("Admin connecté : " + u.getNom() + " " + u.getPrenom());
    }

    private void loadMonthlyReport() {
    try {
        int month = Integer.parseInt(txtMonth.getText().trim());
        int year = Integer.parseInt(txtYear.getText().trim());

        // Appel du service (DAO → DTO)
        MonthlyReportDTO dto = reportService.generateMonthlyReport(year, month);

        // Remplissage résumé
        lblTotalConsultations.setText(String.valueOf(dto.getTotalConsultations()));
        lblTotalRevenue.setText(dto.getTotalRevenue() + " MAD");

        // Remplissage tableau
        DefaultTableModel model = (DefaultTableModel) tableDailyRevenue.getModel();
        model.setRowCount(0);

        for (DailyRevenueDTO d : dto.getDailyRevenues()) {
            model.addRow(new Object[]{
                    d.getDate(),
                    d.getRevenue()
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Erreur ! Vérifiez le mois et l’année.",
                "Erreur", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
private void loadFullReport() {
    try {
        // Récupération de toutes les consultations
        java.util.LinkedList<model.Consultation> all = 
                new ConsultationDAOImpl().findAllConsultations();

        double totalRevenue = 0;
        int totalConsultations = 0;

        // Map pour grouper les revenus par jour
        java.util.Map<java.time.LocalDate, Double> map = new java.util.HashMap<>();

        for (model.Consultation c : all) {
            // On ne considère que les consultations PAYÉES avec une date de paiement
            if (c.isPaid() && c.getDatePaiement() != null) {

                totalRevenue += c.getPrix();
                totalConsultations++;

                java.time.LocalDate d = c.getDatePaiement();
                map.put(d, map.getOrDefault(d, 0.0) + c.getPrix());
            }
        }

        // Mise à jour des labels
        lblTotalConsultations.setText(String.valueOf(totalConsultations));
        lblTotalRevenue.setText(totalRevenue + " MAD");

        // Remplir le tableau
        DefaultTableModel model = (DefaultTableModel) tableDailyRevenue.getModel();
        model.setRowCount(0);

        // Tri des dates (sinon désordre)
        java.util.List<java.time.LocalDate> sorted = new java.util.ArrayList<>(map.keySet());
        java.util.Collections.sort(sorted);

        for (java.time.LocalDate d : sorted) {
            model.addRow(new Object[]{
                    d,
                    map.get(d)
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Erreur lors du chargement du rapport complet.",
                "Erreur", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}


   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblAdminName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalConsultations = new javax.swing.JLabel();
        lblTotalRevenue = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDailyRevenue = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 0, 255));
        lblTitle.setText("RAPPORT MENSUEL");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        lblAdminName.setText("Admin connecté : <nom prénom>");
        getContentPane().add(lblAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 248, -1));

        jLabel6.setText("──────────────────────────────────────────────────────");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel1.setText("Mois / Année :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        txtMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonthActionPerformed(evt);
            }
        });
        getContentPane().add(txtMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 33, -1));

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        getContentPane().add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 73, -1));

        btnSearch.setText("Afficher");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 75, -1));

        jLabel7.setText("────────────────────RÉSUMÉ DU MOIS──────────────────────");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 485, -1));

        jLabel8.setText("───────────────────Revenus journaliers─────────────────────");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 452, -1));

        jLabel9.setText("────────────────────────────────────────────────────");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 446, -1));

        jLabel2.setText("Total consultations :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabel3.setText("Total Revenue :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        lblTotalConsultations.setText(".");
        getContentPane().add(lblTotalConsultations, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 108, -1));

        lblTotalRevenue.setText(".");
        getContentPane().add(lblTotalRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 92, -1));

        btnBack.setText("Retour");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, -1, -1));

        tableDailyRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Revenus (MAD)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDailyRevenue);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, 109));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonthActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String monthText = txtMonth.getText().trim();
        String yearText = txtYear.getText().trim();

    // Si l'un des champs est vide on affiche tout le rapport
    if (monthText.isEmpty() || yearText.isEmpty()) {
        loadFullReport();
        return;
    }

    //  Sinon filtrer normalement
    loadMonthlyReport();

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new AdminDashboard(utilisateur).setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {JOptionPane.showMessageDialog(null,"Veuillez lancer l'application depuis LoginPanel.","Erreur", JOptionPane.ERROR_MESSAGE);});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdminName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalConsultations;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JTable tableDailyRevenue;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
