/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.interfaces.PatientDAO;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import model.Patient;
import model.Role;
import model.Utilisateur;

/**
 *
 * @author idber
 */

public class PatientPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PatientPanel.class.getName());
    private final PatientDAO patientDAO = new dao.impl.PatientDAOImpl();

    private final Utilisateur utilisateur;
    
    


    /**
     * Creates new form ConsultationPanel
     */
    
    public PatientPanel(Utilisateur u) {
    this.utilisateur = u;    
    initComponents();
    loadPatients();
}
    
private void returnToDashboard() {
    if (utilisateur.getRole() == Role.ADMIN) {
        new AdminDashboard(utilisateur).setVisible(true);
    } else if(utilisateur.getRole() == Role.ASSISTANT) {
        new AssistantDashboard(utilisateur).setVisible(true);
    }else if (utilisateur.getRole() == Role.MEDECIN){
        new DoctorDashboard(utilisateur).setVisible(true);
    }
    this.dispose();
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePatients = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Gestion des Patients");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Chercher");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnRefresh.setText("Lister");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tablePatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "cne", "prenom", "nom", "phone", "age", "mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePatients);

        btnAdd.setForeground(new java.awt.Color(0, 102, 51));
        btnAdd.setText("Ajouter");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setForeground(new java.awt.Color(102, 102, 0));
        btnEdit.setText("Modifier");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setForeground(new java.awt.Color(204, 0, 0));
        btnDelete.setText("Supprimer");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("Info patient");

        btnBack.setText("Retour");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(81, 81, 81)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(66, 66, 66)
                                    .addComponent(btnDelete)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnRefresh))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadPatients() {
    try {
        LinkedList<Patient> list = patientDAO.findAllPatients();

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) tablePatients.getModel();

        model.setRowCount(0);

        for (Patient p : list) {
            model.addRow(new Object[]{
                p.getId(),
                p.getCne(),
                p.getPrenom(),
                p.getNom(),
                p.getPhone(),
                p.getAge(),
                p.getMail()
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur chargement patients");
        e.printStackTrace();
    }
}
    

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
       String keyword = txtSearch.getText().trim();

    try {
        LinkedList<Patient> list = patientDAO.searchPatientByName(keyword);

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) tablePatients.getModel();

        model.setRowCount(0);

        for (Patient p : list) {
            model.addRow(new Object[]{
                p.getId(),
                p.getCne(),
                p.getPrenom(),
                p.getNom(),
                p.getPhone(),
                p.getAge(),
                p.getMail()
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur recherche !");
        e.printStackTrace();
    }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         String keyword = txtSearch.getText().trim();

    try {
        LinkedList<Patient> list = patientDAO.searchPatientByName(keyword);

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) tablePatients.getModel();

        model.setRowCount(0);

        for (Patient p : list) {
            model.addRow(new Object[]{
                p.getId(),
                p.getCne(),
                p.getPrenom(),
                p.getNom(),
                p.getPhone(),
                p.getAge(),
                p.getMail()
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur recherche !");
        e.printStackTrace();
    }

        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String cne = JOptionPane.showInputDialog(this, "CNE :");
    if (cne == null) return;

    String prenom = JOptionPane.showInputDialog(this, "Prénom :");
    String nom = JOptionPane.showInputDialog(this, "Nom :");
    String phone = JOptionPane.showInputDialog(this, "Téléphone :");
    String ageStr = JOptionPane.showInputDialog(this, "Âge :");
    String mail = JOptionPane.showInputDialog(this, "Email :");

    try {
        int age = Integer.parseInt(ageStr);

        Patient p = new Patient(cne, prenom, nom, phone, age, mail);

        if (patientDAO.createPatient(p)) {
            JOptionPane.showMessageDialog(this, "Patient ajouté !");
            loadPatients();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur ajout !");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
          int row = tablePatients.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un patient.");
        return;
    }

    int id = (int) tablePatients.getValueAt(row, 0);

    try {
        Patient p = patientDAO.findPatientById(id);

        String cne = JOptionPane.showInputDialog(this, "CNE :", p.getCne());
        if (cne == null) return;

        String prenom = JOptionPane.showInputDialog(this, "Prénom :", p.getPrenom());
        String nom = JOptionPane.showInputDialog(this, "Nom :", p.getNom());
        String phone = JOptionPane.showInputDialog(this, "Téléphone :", p.getPhone());
        String ageStr = JOptionPane.showInputDialog(this, "Âge :", p.getAge());
        String mail = JOptionPane.showInputDialog(this, "Email :", p.getMail());

        p.setCne(cne);
        p.setPrenom(prenom);
        p.setNom(nom);
        p.setPhone(phone);
        p.setAge(Integer.parseInt(ageStr));
        p.setMail(mail);

        if (patientDAO.updatePatient(p)) {
            JOptionPane.showMessageDialog(this, "Modifié !");
            loadPatients();
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erreur modification !");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tablePatients.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un patient.");
        return;
    }

    int id = (int) tablePatients.getValueAt(row, 0);

    int confirm = JOptionPane.showConfirmDialog(this,
            "Supprimer ce patient ?", "Confirmation",
            JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            if (patientDAO.deletePatient(id)) {
                JOptionPane.showMessageDialog(this, "Supprimé !");
                loadPatients();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur suppression !");
            e.printStackTrace();
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        returnToDashboard();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadPatients();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePatients;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
